name: core

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Cache .m2
        uses: actions/cache@v2.1.6
        with:
          path: "~/.m2/repository"
          key: ${{ runner.os }}-m2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: 3.6.0

      - name: Install example projects
        run: ./.github/install_examples.sh
        shell: bash

      - name: Run tests
        run: |
          cd nopol
          mvn clean test

      - name: Codecov
        uses: codecov/codecov-action@v1.5.2
