name: intellij

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Cache .m2
        uses: actions/cache@v2.1.6
        with:
          path: "~/.m2/repository"
          key: ${{ runner.os }}-m2

      - name: Setup JDK8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'adopt'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: 3.6.0

      - name: Install example projects
        run: ./.github/install_examples.sh
        shell: bash

      - name: Install nopol
        run: |
          cd nopol
          mvn clean install -DskipTests

      - name: Install nopol-server
        run: |
          cd nopol-server
          mvn clean install -DskipTests

      - name: Compile and test nopol-ui-intellij
        run: |
          cd nopol-ui-intellij
          ./gradlew buildPlugin
